import RPi.GPIO as GPIO
from time import sleep

GPIO.setmode(GPIO.BOARD)

GPIO.setwarnings(False)

GPIO.setup(8,  GPIO.OUT, initial=GPIO.LOW)
GPIO.setup(19, GPIO.OUT, initial=GPIO.LOW)
GPIO.setup(10, GPIO.OUT, initial=GPIO.LOW)
GPIO.setup(11, GPIO.OUT, initial=GPIO.LOW)
GPIO.setup(12, GPIO.OUT, initial=GPIO.LOW)
GPIO.setup(13, GPIO.OUT, initial=GPIO.LOW)
GPIO.setup(7,  GPIO.OUT, initial=GPIO.LOW)
GPIO.setup(15, GPIO.OUT, initial=GPIO.LOW)
GPIO.setup(16, GPIO.OUT, initial=GPIO.LOW)
GPIO.setup(18, GPIO.OUT, initial=GPIO.LOW)
GPIO.setup(22, GPIO.OUT, initial=GPIO.LOW)
 
while True:
    sleep(1)
    GPIO.output(8, GPIO.HIGH)
    sleep(1)
    GPIO.output(19, GPIO.HIGH)
    sleep(1)
    GPIO.output(10, GPIO.HIGH)
    sleep(1)
    GPIO.output(11, GPIO.HIGH)
    sleep(1)
    GPIO.output(12, GPIO.HIGH)
    sleep(1)
    GPIO.output(13, GPIO.HIGH)
    sleep(1)
    GPIO.output(7, GPIO.HIGH)
    sleep(1)
    GPIO.output(15, GPIO.HIGH)
    sleep(1)
    GPIO.output(16, GPIO.HIGH)
    sleep(1)
    GPIO.output(22, GPIO.HIGH)
    sleep(0.5)
    GPIO.output(8,  GPIO.LOW)
    GPIO.output(19, GPIO.LOW)
    GPIO.output(10, GPIO.LOW)
    GPIO.output(11, GPIO.LOW)
    GPIO.output(12, GPIO.LOW)
    GPIO.output(13, GPIO.LOW)
    GPIO.output(7,  GPIO.LOW)
    GPIO.output(15, GPIO.LOW)
    GPIO.output(16, GPIO.LOW)
    GPIO.output(22, GPIO.LOW)
    sleep(0.5)
    GPIO.output(8,  GPIO.HIGH)
    GPIO.output(19, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(11, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)
    GPIO.output(13, GPIO.HIGH)
    GPIO.output(7,  GPIO.HIGH)
    GPIO.output(15, GPIO.HIGH)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(22, GPIO.HIGH)
    sleep(0.5)
    GPIO.output(8,  GPIO.LOW)
    GPIO.output(19, GPIO.LOW)
    GPIO.output(10, GPIO.LOW)
    GPIO.output(11, GPIO.LOW)
    GPIO.output(12, GPIO.LOW)
    GPIO.output(13, GPIO.LOW)
    GPIO.output(7,  GPIO.LOW)
    GPIO.output(15, GPIO.LOW)
    GPIO.output(16, GPIO.LOW)
    GPIO.output(22, GPIO.LOW)
    sleep(0.5)
    GPIO.output(8,  GPIO.HIGH)
    GPIO.output(19, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(11, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)
    GPIO.output(13, GPIO.HIGH)
    GPIO.output(7,  GPIO.HIGH)
    GPIO.output(15, GPIO.HIGH)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(22, GPIO.HIGH)
    sleep(0.5)
    GPIO.output(8,  GPIO.LOW)
    GPIO.output(19, GPIO.LOW)
    GPIO.output(10, GPIO.LOW)
    GPIO.output(11, GPIO.LOW)
    GPIO.output(12, GPIO.LOW)
    GPIO.output(13, GPIO.LOW)
    GPIO.output(7,  GPIO.LOW)
    GPIO.output(15, GPIO.LOW)
    GPIO.output(16, GPIO.LOW)
    GPIO.output(22, GPIO.LOW)
    sleep(0.5)
